apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: github
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: github-provider-creds
      key: credentials
