apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - n8n-claim0-persistentvolumeclaim.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - namespace.yaml
  - postgres-claim0-persistentvolumeclaim.yaml
  - postgres-configmap.yaml
  - postgres-deployment.yaml
  - postgres-sealed-secret.yaml
  - postgres-service.yaml
