apiVersion: v1
kind: Secret
metadata:
  name: localstack-creds
stringData:
  credentials: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
---
apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  endpoint:
    hostnameImmutable: true
    services: [ec2, iam, s3, sqs, sns, sts, elasticache]
    url:
      type: Static
      static: http://localstack.localstack:4566
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-creds
      key: credentials
  skip_credentials_validation: true
  skip_metadata_api_check: true
  s3_use_path_style: true
