apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: localstack
    repo: https://localstack.github.io/helm-charts
    version: 0.6.26
    releaseName: localstack
    namespace: localstack
