---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: proxmox-cloud-controller-manager
spec:
  encryptedData:
    config.yaml: AgCOfw2kSiTy29P0HUenzHYPTo8JVKtzT9cnPmlFYA2ZTnCGvwwNjngyrYHiflQ9+Hp7C3DGH14WdFzd4TXd13QYojt5XlSUtGbFNnyIYOOmWJMeLoEtsn3jXUBgvmaFRcoCLX5aXiGhf/lzP889tbtaXPnKjI/VM2Avcb9DUBTrqIOYOlbMnQamJlNAbXCB5rhZYjxG5igLNLPHCDtWJFUIfmUWaJONA/R+1lcw7Va6Wt4pJeaypGcFwz33g9/ZbOzwb5tNwJvkLUlNtw289uUKEYseDrYRGD6ynrausxmNCn4bszRW22ZVah2WWW2vP0IMuIoMWY/pigoRh0yL6eYwbia1hEtLFvPVki1iLZEsOXjY7evv6PDwSErI8YDozGq69B6Oh67UFzPan1U+OmyWAQ3Csc7YRPNzeV7TBUa1ig0mTCm4TmiJWCjIYgMKPJ2P5T/egGBYaxWx05mNJNwwMMEg7MjGNPIhxbCOIlXQypI+oYjQ5i6/IUCo5dNY4Nyz8Tym/C+d97RO4clH6NE+iJcgfrzTcN6lg+l9MgXFGd30r4/DqUejIjGEQVmwDeNET6Y9DIaJ06I6zG0OGiJ2pWmLpyJOv66Z5AK4k02Gmd95X8kXDFh8xKjAE3TWlyMuApJPKcgblG1PwUxZrYwsPncswGzh4oK7njhjh+EHAv6b90omxXP2ofwx7b0to0BDrONaoEifok/LI9WiH0E4KcrkMGnFh0bknv/G/tEBXW+N9AqhHONDfndalKjSgJJRwEAk3L89k/9hoYKDiHVnJqbS3fccKVM83qrvrmr1KO+IhoUnDI+2F4DoIYHIC4v4wnVKS9gDou+PgmAslCqaaFYYChJFIJjPQfmhLVKnEYOjGgg9Podppcb/xYx3D3rsTGI/9DuaZnORR4mOhyWh3kpysljmpP5ApLWHjGE4b0OdchvfFl5sNw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: proxmox-cloud-controller-manager
      namespace: kube-system
