apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: pocket-id
    repo: https://anza-labs.github.io/charts
    version: 1.7.4
    releaseName: pocket-id
    namespace: pocket-id
    valuesInline:
      analyticsDisabled: true
      pocketID:
        image:
          tag: v2.2.0
      ingress:
        enabled: true
        host: id.homelab.kszpakowski.com
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        tls:
          - secretName: pocket-id-cert
            hosts:
              - id.homelab.kszpakowski.com
      persistence:
        data:
          enabled: true
