apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: crossplane
    repo: https://charts.upbound.io/stable
    version: 2.0.2-up.1
    releaseName: crossplane
    namespace: crossplane-system
    valuesInline:
      provider:
        defaultActivations: []
      